#!/bin/bash

/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc -c main.c -mthumb-interwork -mthumb -O2 -o main.o
/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc main.o -mthumb-interwork -mthumb -specs=gba.specs -o main.elf
/opt/devkitpro/devkitARM/bin/arm-none-eabi-objcopy -v -O binary main.elf main.gba
/opt/gba-tools/gbafix main.gba
